services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linebot-backend
    volumes:
      - ./app:/app
    environment:
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LOG_DIR=${LOG_DIR}
      - DB_DIR=${DB_DIR}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8000:8000"
    networks:
      - bot-network

  ngrok:
    image: ngrok/ngrok:3
    container_name: linebot-ngrok
    restart: always
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "backend:8000"
    networks:
      - bot-network
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:0.18.3
    container_name: linebot-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      #- /root/.ollama:/root/.ollama # 在linux 環境下使用
      - ./ollama:/root/.ollama # 在mac 環境下使用
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: linebot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
